### ISSUE TITLE
Bad checksum for cjk font

### ISSUE THREAD

**Issue by Alsan** [kenshaw/fv#2] opened 2024-11-09 03:31 UTC
```bash
 fv "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc"
```

generates output:
```console
"Noto Sans CJK Regular": /usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc -- error: bad checksum
```

**Comment by kenshaw** [comment] 2024-11-09 04:44
@Alsan I'm glad someone is making use of the app! 

This is a limitation of the font package that is being used, as such it's outside of the scope of what I can fix. For what it's worth, `fv` uses the [canvas](https://github.com/tdewolff/canvas) package for loading and rendering fonts, which makes use of its own [font](https://github.com/tdewolff/font) package for decoding font files.

Closing this, as the issue is with the dependency.

**Closed as completed by kenshaw** 2024-11-09 04:44 UTC
